{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Średnia krocząca semantyki polityków (500 próbek)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH RankedRatings AS (\r\n    SELECT\r\n        politician,\r\n        rating,\r\n        ROW_NUMBER() OVER (PARTITION BY politician ORDER BY timestamp DESC) AS row_num\r\n    FROM\r\n        politicians\r\n    WHERE\r\n        politician IN ('trump', 'clinton', 'obama','sanders')\r\n)\r\nSELECT\r\n    politician,\r\n    AVG(rating) AS average_rating\r\nFROM\r\n    RankedRatings\r\nWHERE\r\n    row_num <= 500\r\nGROUP BY\r\n    politician;\r\n"
    }
   ]
  },
  {
   "title": "Semantyka tweetów wybranych polityków w rozdzielczości dziennej",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('day', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS obama\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'obama'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('day', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS trump\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'trump'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('day', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS sanders\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'sanders'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('day', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS clinton\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'clinton'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Średnia semantyki polityków",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    politician,\r\n    AVG(rating) AS average_rating\r\nFROM\r\n    politicians \r\nWHERE\r\n    politician IN ('obama', 'trump', 'clinton','sanders')\r\nGROUP BY\r\n    politician;\r\n"
    }
   ]
  },
  {
   "title": "Semantyka tweetów wybranych polityków w rozdzielczości tygodniowej",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS obama\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'obama'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS trump\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'trump'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS sanders\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'sanders'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', TIMESTAMP 'epoch' + CAST(timestamp AS bigint) * INTERVAL '1 second') AS week_timestamp,\r\n    AVG(rating) AS clinton\r\nFROM \r\n    politicians\r\nWHERE \r\n    politician = 'clinton'\r\nGROUP BY \r\n    week_timestamp\r\nORDER BY \r\n    week_timestamp;\r\n"
    }
   ]
  }
 ]
}