# Use the Bitnami Spark image as the base image
FROM bitnami/spark:3.2.1

USER root

RUN pip install numpy
RUN pip install kafka-python
RUN pip install vaderSentiment

# Set the working directory
WORKDIR /
