# Use the Bitnami Spark image as the base image
FROM bitnami/spark:3.2.1

USER root

RUN pip install numpy
RUN pip install pandas
RUN pip install kafka-python
RUN pip install vaderSentiment
RUN pip install pyarrow


# Set the working directory
WORKDIR /
